# brisas.toml
[terminal]
nombre = "Terminal Principal"
id = "" # Se genera autom√°ticamente basado en hardware

[database]
# Rutas a intentar en orden de prioridad
paths = [
    "./data/brisas.db",
    "C:/ProgramData/Brisas/brisas.db",
    "${APPDATA}/Brisas/brisas.db"
]
# Ruta por defecto si no existe ninguna
default_path = "${USERPROFILE}/.brisas/brisas.db"

[app]
version = "0.1.0"